server:
  port: 10010
spring:
  application:
    name: grain-breeze-gateway-10010
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: grain-breeze-service-route
          uri: lb://grain-breeze-elegance-main-10011
          predicates:
            - Path=/api/grain/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: grain-breeze-oss-route
          uri: lb://grain-breeze-elegance-service-10012
          predicates:
            - Path=/api/service/**
          filters: # /api/service/** -> /**
            - RewritePath=/api/service/(?<segment>.*), /$\{segment}
