server:
  port: 10010
spring:
  data:
    redis:
      port: 6379
      host: 192.168.56.100
      connect-timeout: 10000ms
      lettuce:
        pool:
          max-wait: 10000ms
          max-idle: 200
          min-idle: 5
          max-active: 8
  application:
    name: grain-breeze-gateway-10010
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 169c3500-d0c4-431b-aa22-b0b33d8f7b74
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: grain-breeze-service-route
          uri: lb://grain-breeze-elegance-main-10011
          predicates:
            - Path=/api/grain/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: grain-breeze-oss-route
          uri: lb://grain-breeze-elegance-service-10012
          predicates:
            - Path=/api/service/**
          filters: # /api/service/** -> /**
            - RewritePath=/api/service/(?<segment>.*), /$\{segment}
