server:
  port: 10010
spring:
  application:
    name: GrainBreezeGateway-10010
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos